### ISSUE TITLE
[question] About the DB support

### ISSUE THREAD

**Issue by ItsCEED** [NuclearRazor/csgo_parser#4]
When the DB Support will be published?

**Comment by NuclearRazor** [comment]
Hi, what do you mean "DB Support"?

Main algorithms are using sqllite3, but output data is only in *.csv format. I think this is enought at now, but i'll be write some updates in a few weeks. 

If you want to ask any question - you are welcome!

**Comment by ItsCEED** [comment]
@NuclearRazor aww thats good to hear, i hope that comparing data's between item shops and item exchangers will come soon. Till that point i guess ill transform the csv in to sql and do the math in php since im noob in python :(

Uh, and how to make the prices in US/EUR? 🗡 

edit3. I guess the price comparation is up and running, but im always getting empty files :/ Is it me doing something wrong?

edit4: Could you make comparation for the exchange sites? To see if we can make profit if we get something from one and trade it to another? Just educational and math..

**Comment by NuclearRazor** [comment]
"hope that comparing data's between item shops and item exchangers will come soon" - it is also on **master branch** or **quiet_version**.

I made a price conversion to rubles, if you want to get data without it, you must edit existing code in parser.py (master branch or quiet_version branch):

**convert_course** = self.csmoney_usd_course()

This is get price of cost of 1 Dollar USD to 1 Ruble RUS, write convert_course = 1 and you see prices only in USD. I don't think that this is hard to change.

" I guess the price comparation is up and running" - there a few methods of sorting data, you can regulate prices bounds, profit bounds, to see what sorting are there - go to get_select_with_sort_param() in db.py. Maybe you set up non empiric bounds or etc and get empty files.

"Could you make comparation for the exchange sites?" - you can see _old commits_ in master or database_oop, there was comparing data in model - like an graph with unique vertex. 

(Now we have two categories - shops and exhangers, because 1 trade cycle are often exist between 1 shop and 1 exhanger and not anything else - empiric rule you know).

**P. S.**

I write on Python because i can fastly get working prototype by using it. If i have had a good tests, maybe i write some specific logic on C++ or C#, but anyway this is not necessary yet.

**Comment by ItsCEED** [comment]
seems like i cant fix it, but you da real mvp!

**Comment by NuclearRazor** [comment]
I'll add some instructions to Readme, please let me know if you find any bugs.

Close issue?

**Comment by ItsCEED** [comment]
All cool! Thanks! Also any possible way to get your steam ID? :P

**Comment by NuclearRazor** [comment]
Write me e-mail)
